CREATE SCHEMA  IF NOT EXISTS ESTACIONAMENTO;

CREATE TABLE  tbl_usuario(
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Parque(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CAPACIDADE_MAXIMA INT NULL,
	VAGAS_DISPONIVEIS INT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE  tbl_movimentacao(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MODELO VARCHAR(10) NOT NULL,
	PLACA VARCHAR(10),
    TIPO_VEICULO VARCHAR(10) NULL DEFAULT NULL,
	CLIENTE_ID BIGINT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT 
	FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE (ID)
);

CREATE TABLE tbl_movimentacao2(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DATA_ENTRADA DATE,
	DATA_SAIDA DATE,
	HORA_ENTRADA TIME ,
	HORA_SAIDA TIME ,
	PARQUE_ID BIGINT,
	VEICULO_ID BIGINT,
	PRIMARY KEY (ID),
	CONSTRAINT 
    FOREIGN KEY (PARQUE_ID)
    REFERENCES PARQUE (ID),
	CONSTRAINT 
    FOREIGN KEY (VEICULO_ID)
    REFERENCES VEICULO (ID)
);

CREATE TABLE tbl_valor(
  TIPO_VEICULO VARCHAR(10) NOT NULL,
  PRECO_HORA DOUBLE NOT NULL,
  PRECO_HORA_FRACAO DOUBLE NOT NULL,
  PRIMARY KEY (TIPO_VEICULO)
);

CREATE TABLE  Ticket(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  VEICULO_PLACA VARCHAR(10) NOT NULL,
  DATA_ENTRADA DATE NOT NULL,
  DATA_SAIDA DATE NOT NULL,
  HORA_ENTRADA TIME NOT NULL,
  HORA_SAIDA TIME NOT NULL,
  NOME_CLIENTE VARCHAR(45) NOT NULL,
  PRECO_HORA DOUBLE NOT NULL,
  PRECO_VEICULO VARCHAR(10) NOT NULL,
  VALOR_TOTAL DOUBLE NOT NULL,
  PARQUE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT 
	FOREIGN KEY (PARQUE_ID)
    REFERENCES PARQUE (ID)
);


